  DROP TABLE ECO_EDU CASCADE CONSTRAINT;
  DROP TABLE EDICION CASCADE CONSTRAINT;
  DROP TABLE PISA CASCADE CONSTRAINT;
  DROP TABLE ZONA CASCADE CONSTRAINT;
  
  
  CREATE TABLE ZONA 
   (	COUNTRY_NAME VARCHAR2(50 BYTE), 
	COUNTRY_CODE VARCHAR2(26 BYTE), 
	REGION VARCHAR2(128 BYTE), 
	 CONSTRAINT PKZ PRIMARY KEY (COUNTRY_CODE, COUNTRY_NAME));  
     
     
  CREATE TABLE "SYSTEM"."ECO_EDU" 
   (	"COUNTRY_NAME" VARCHAR2(50 BYTE), 
	"COUNTRY_CODE" VARCHAR2(26 BYTE), 
	"MEAN_GDPCAPITA" NUMBER(38,2), 
	"GASTOXALUMNOGDPCAPITA" NUMBER(38,2), 
	"RATIO_ALUM_PROF" NUMBER(38,2), 
	 CONSTRAINT "PKECO" PRIMARY KEY ("COUNTRY_CODE",COUNTRY_NAME),
     CONSTRAINT FK_EC1 FOREIGN KEY ("COUNTRY_CODE") REFERENCES ZONA(COUNTRY_CODE) ON DELETE CASCADE,
     CONSTRAINT FK_EC2 FOREIGN KEY ("COUNTRY_NAME") REFERENCES ZONA(COUNTRY_NAME) ON DELETE CASCADE);
    
      CREATE TABLE "SYSTEM"."EDICION" 
   (	"EDICION" VARCHAR2(26 BYTE), 
	"ANYO" NUMBER(38,0), 
	"NUM_PARTIC" NUMBER(38,0), 
	 CONSTRAINT "PK_EDICION" PRIMARY KEY ("EDICION"));
     
CREATE TABLE "SYSTEM"."PISA" 
   (	"PAIS" VARCHAR2(50 BYTE), 
	"CODE" VARCHAR2(26 BYTE), 
	"EDICION" VARCHAR2(26 BYTE), 
	"MATHS" NUMBER(38,2), 
	"READING" NUMBER(38,2), 
	"SCIENCE" NUMBER(38,2),
    CONSTRAINT "PKPISA" PRIMARY KEY ("CODE",EDICION,PAIS),
    CONSTRAINT FK_P1 FOREIGN KEY (PAIS) REFERENCES ZONA(COUNTRY_NAME) ON DELETE CASCADE,
     CONSTRAINT FK_P1 FOREIGN KEY ("CODE") REFERENCES ZONA(COUNTRY_CODE) ON DELETE CASCADE,
     CONSTRAINT FK_P2 FOREIGN KEY ("EDICION") REFERENCES EDICION(EDICION) ON DELETE CASCADE) ;
   

#INSERTAR DATOS CON WIZARD
     
     
#8

SELECT PAIS, SUM(MATHS), 
DENSE_RANK () OVER (ORDER BY SUM(Maths) DESC) AS D_RANK, 
RANK() OVER (ORDER BY SUM(Maths) DESC) AS RANK
FROM PISA GROUP BY PAIS;

#9

SELECT COUNTRY_NAME, RATIO_ALUM_PROF, 
LAG (RATIO_ALUM_PROF, 1,0 ) OVER ( ORDER BY RATIO_ALUM_PROF) AS ALUMXPROF_PREV,
LEAD (RATIO_ALUM_PROF, 1,0 ) OVER (ORDER BY RATIO_ALUM_PROF) AS ALUMXPROF_NEXT
FROM ECO_EDU  GROUP BY COUNTRY_NAME,RATIO_ALUM_PROF;


SELECT  Z.Region,
MIN(P.Reading) KEEP (DENSE_RANK FIRST ORDER BY P.READING) AS PEOR_RESULTADO, 
MAX(P.Reading) KEEP (DENSE_RANK LAST ORDER BY P.READING) AS MEJOR_RESULTADO 
FROM ZONA Z JOIN PISA P ON Z.COUNTRY_CODE = P.CODE  WHERE P.EDICION = 'Primera' GROUP BY Z.REGION ;

#10

SELECT Z.REGION, EC.COUNTRY_NAME, EC.MEAN_GDPCAPITA, P.READING,
ROUND(REGR_R2(EC.MEAN_GDPCAPITA, P.READING) OVER (PARTITION BY Z.REGION),3)AS R2
FROM ECO_EDU EC JOIN PISA P ON EC.COUNTRY_CODE = P.CODE JOIN ZONA Z ON Z.COUNTRY_CODE = P.CODE WHERE P.EDICION = 'Primera';





